name: xzitpocket
description: "掌上徐工"
publish_to: 'none'
version: 2.0.2+2002

environment:
  sdk: ^3.13.0

dependencies:
  flutter:
    sdk: flutter

  flutter_riverpod: ^3.4.2
  dio: ^5.11.0
  cookie_jar: ^4.0.9
  dio_cookie_manager: ^3.5.0
  pointycastle: ^4.0.0
  crypto: ^3.0.7
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  shared_preferences: ^2.5.5
  flutter_secure_storage: ^11.0.0
  connectivity_plus: ^7.3.1
  package_info_plus: ^10.2.1
  home_widget: ^0.9.3
  html: ^0.15.6
  path: ^1.9.1
  sqflite: ^2.4.3
  flutter_markdown_plus: ^1.0.12
  image_picker: ^1.2.3
  image: ^4.9.1
  talker_flutter: ^5.1.20
  talker_dio_logger: ^5.1.20
  forui: 0.25.0
  url_launcher: ^6.3.2
  open_filex: ^4.7.0
  path_provider: ^2.1.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - fmd/power/room.db
    - assets/tutorials/
