[zx]
url = "http://211.87.126.94/zx"
price = "0.54"

[cn]
url = "http://211.87.126.94/cn"
price = "0.54"

[dxq]
url = "http://211.87.126.249/dxq"
price = "0.54"

[server]
request_timeout = 3
host = "127.0.0.1"
port = 8000
est_days_min = 5
